Repository ucsb-cs156-s23/proj-courses-s23-7pm-3, pull requests merged in 2023-06, with the labels that each got.

#23 Bug Fix - Search function doesn't work on default subject without switching from another 7pm-3
  frontend/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  frontend/src/main/components/BasicCourseSearch/CourseOverTimeSearchForm.js
Labels: s23-7pm-3, Merge Candidate

#35 hx -Break one : added upload history grade services and all needed models
  pom.xml
  src/main/java/edu/ucsb/cs156/courses/entities/GradeHistory.java
  src/main/java/edu/ucsb/cs156/courses/models/ApiResult.java
  src/main/java/edu/ucsb/cs156/courses/models/TreeElement.java
  src/main/java/edu/ucsb/cs156/courses/repositories/GradeHistoryRepository.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBGradeHistoryService.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBGradeHistoryServiceImpl.java
  src/test/java/edu/ucsb/cs156/courses/entities/GradeHistoryTests.java
  src/test/java/edu/ucsb/cs156/courses/fixtures/GradeHistoryFixtures.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBGradeHistoryServiceTests.java
Labels: s23-7pm-3

#53 hx - Add backend endpoint for uploading grade history data to database
  src/main/java/edu/ucsb/cs156/courses/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/courses/jobs/UploadGradeDataJob.java
  src/main/java/edu/ucsb/cs156/courses/jobs/UploadGradeDataJobFactory.java
  src/test/java/edu/ucsb/cs156/courses/controllers/JobsControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/jobs/UploadGradeDataJobFactoryTests.java
  src/test/java/edu/ucsb/cs156/courses/jobs/UploadGradeDataJobTests.java
Labels: s23-7pm-3

#42 yl - Create form component for instructor-based search
  frontend/src/main/components/BasicCourseSearch/CourseOverTimeInstructorSearchForm.js
  frontend/src/stories/components/BasicCourseSearch/CourseOverTimeInstructorSearchForm.stories.js
  frontend/src/tests/components/BasicCourseSearch/CourseOverTimeInstructorSearchForm.test.js
Labels: s23-7pm-3, Merge Candidate - CI/CD

#45 kt - Add files for dropdown menu (Building Search 1/3)
  frontend/src/fixtures/buildingFixtures.js
  frontend/src/main/components/Buildings/SingleBuildingDropdown.js
  frontend/src/stories/components/Buildings/SingleBuildingDropdown.stories.js
  frontend/src/tests/components/Buildings/SingleBuildingDropdown.test.js
  scripts/README.md
  scripts/getAllBuildings.py
Labels: s23-7pm-3, 10, Merge Candidate - CI/CD

#52 yl - Add index page for instructor-based search
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/CourseOverTime/CourseOverTimeInstructorIndexPage.js
  frontend/src/stories/pages/CourseOverTimeInstructorIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/CourseOverTime/CourseOverTimeInstructorIndexPage.test.js
Labels: s23-7pm-3, 10

#55 nz - Added error messages to PSCourseCreatePage + tests
  frontend/src/main/pages/Courses/PSCourseCreatePage.js
  frontend/src/tests/pages/Courses/CoursesCreatePage.test.js
Labels: s23-7pm-3, 10

#59 hx -added GET endpoint of gradehistory controller and related utilities
  src/main/java/edu/ucsb/cs156/courses/controllers/GradeHistoryController.java
  src/main/java/edu/ucsb/cs156/courses/utilities/CourseUtilities.java
  src/test/java/edu/ucsb/cs156/courses/controllers/GradeHistoryControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/utilities/CourseUtilitiesTests.java
Labels: s23-7pm-3, MERGE CANDIDATE - testing on staff-qa
