Repository ucsb-cs156-s23/proj-courses-s23-7pm-3, pull requests merged in 2023-05, with the labels that each got.

#17 Changed color of Navbar to UCSB Blue
  frontend/src/index.css
  frontend/src/main/components/Nav/AppNavbar.js
Labels: s23-7pm-3, 5

#19 Implement API endpoints for Building Search
  src/main/java/edu/ucsb/cs156/courses/collections/ConvertedSectionCollection.java
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeBuildingController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeBuildingControllerTests.java
Labels: s23-7pm-3

#21 hx - added history eneity and repository
  src/main/java/edu/ucsb/cs156/courses/entities/GradeHistory.java
  src/main/java/edu/ucsb/cs156/courses/repositories/GradeHistoryRepository.java
Labels: s23-7pm-3, 5

#18 Implement backend endpoint for search by instructor
  src/main/java/edu/ucsb/cs156/courses/collections/ConvertedSectionCollection.java
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeInstructorController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeInstructorControllerTests.java
Labels: s23-7pm-3, MERGE CANDIDATE - testing on staff-qa

#22 Navbar improvement
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
Labels: s23-7pm-3, 10

#28 Update README.md
  README.md
Labels: s23-7pm-3

#29 Add @ApiParam annotations to existing CourseOverTimeController.java file
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeController.java
Labels: s23-7pm-3, 5
